name: Caller Workflow
on:
  push:
    branches:
      - master
jobs:
  reusable-1:
    uses: ./.github/workflows/reusable-workflow.yaml
    with:
      node-version: '20'
      run-tests: true
    secrets:
      TOKEN: '${{ secrets.GITHUB_TOKEN }}'
  reusable-2:
    uses: ./.github/workflows/reusable-workflow-2.yaml
    with:
      node-version: '20'
      run-tests: false
    secrets:
      TOKEN: '${{ secrets.GITHUB_TOKEN }}'
