name: PROD - OIDC build artifact

on: [workflow_dispatch]
  
jobs:
  run-go-action:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run My Custom Go Action
        id: artifact
        uses: cloudbees-io-gha/register-build-artifact@main
        # uses: ./
        with:
          name: "oidc-artifact-prod"
          version: 1.0.0
          url: "ghcr.io/hemaladev57/testaction/prod-artifact:latest"
          digest: "sha256:566b1117a16243a43be01e378a20ee823c95d00cd5f3231ad4d168f53d99d9d8"
          type: "docker"
          label: 'verified,prod'

      - name: Test output
        run: echo '${{ steps.artifact.outputs.cbp_artifact_id }}'
